import '../style/style.css';
import '../style/modern-normalize.css';
import '../style/utles.css';
import '../style/components/header.css';
import '../style/components/parallex.css';
import '../style/components/about.css';
import '../style/components/flipbook.css';
import './flipbook.js'
import './parallax.js'
import './slider.js'
import '../style/components/footer.css';